### ISSUE TITLE
Configuration does not save properly 

### ISSUE THREAD

**Issue by MartinLPetrauskas** [briweinstein/OpenWrt-IoT-IDS-Privacy#17]
In doing some basic testing of tinyHIPPO, there are some issues with the Config page not saving values properly.

```
{
   "virustotal_api_key": "TEMPLATE",
   "mac_addrs": [
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69",
     "d4:a6:51:40:1d:69"
   ],
   "alert_collection_path": "\/etc\/tinyHIPPO\/alert_collection.json",
   "email": {
     "email_password": "super_secure_password",
     "email_account": "openwrt@example.com",
     "smtp_server": "smtp.example.com",
     "recipient_emails": [
       "homeowner@example.com"
     ]
   }
 }
```

The two issues are that the proper MAC addresses are not written. It just repeats the first one on the list.

Second issue is that the alert_collection_path variable is wonky. I don't know what is going on with the backslash and forward slashes.

**Comment by lucas-m98** [comment]
Should be all fixed in the newest PR. MAC addresses were not being properly labeled in the HTML and apparently the `luci.jsonc.stringify` function makes the JSON string it outputs Lua safe so it escapes on forward slashes.
